//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSMessages
{
    [Serializable]
    public class MoveCubeResultMsg : Message
    {
        public const string k_RosMessageName = "practice_msgs/MoveCubeResult";
        public override string RosMessageName => k_RosMessageName;

        public string result_message;

        public MoveCubeResultMsg()
        {
            this.result_message = "";
        }

        public MoveCubeResultMsg(string result_message)
        {
            this.result_message = result_message;
        }

        public static MoveCubeResultMsg Deserialize(MessageDeserializer deserializer) => new MoveCubeResultMsg(deserializer);

        private MoveCubeResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result_message);
        }

        public override string ToString()
        {
            return "MoveCubeResultMsg: " +
            "\nresult_message: " + result_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
