//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSMessages
{
    [Serializable]
    public class MoveCubeFeedbackMsg : Message
    {
        public const string k_RosMessageName = "practice_msgs/MoveCubeFeedback";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg current_pose;

        public MoveCubeFeedbackMsg()
        {
            this.current_pose = new Geometry.PoseMsg();
        }

        public MoveCubeFeedbackMsg(Geometry.PoseMsg current_pose)
        {
            this.current_pose = current_pose;
        }

        public static MoveCubeFeedbackMsg Deserialize(MessageDeserializer deserializer) => new MoveCubeFeedbackMsg(deserializer);

        private MoveCubeFeedbackMsg(MessageDeserializer deserializer)
        {
            this.current_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_pose);
        }

        public override string ToString()
        {
            return "MoveCubeFeedbackMsg: " +
            "\ncurrent_pose: " + current_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
