//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSMessages
{
    [Serializable]
    public class CallMoveCubeASRequest : Message
    {
        public const string k_RosMessageName = "practice_msgs/CallMoveCubeAS";
        public override string RosMessageName => k_RosMessageName;

        public PoseOriginTargetMsg pose_origin_target;

        public CallMoveCubeASRequest()
        {
            this.pose_origin_target = new PoseOriginTargetMsg();
        }

        public CallMoveCubeASRequest(PoseOriginTargetMsg pose_origin_target)
        {
            this.pose_origin_target = pose_origin_target;
        }

        public static CallMoveCubeASRequest Deserialize(MessageDeserializer deserializer) => new CallMoveCubeASRequest(deserializer);

        private CallMoveCubeASRequest(MessageDeserializer deserializer)
        {
            this.pose_origin_target = PoseOriginTargetMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_origin_target);
        }

        public override string ToString()
        {
            return "CallMoveCubeASRequest: " +
            "\npose_origin_target: " + pose_origin_target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
