//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSMessages
{
    [Serializable]
    public class HeightTestResponse : Message
    {
        public const string k_RosMessageName = "practice_msgs/HeightTest";
        public override string RosMessageName => k_RosMessageName;

        public bool result;

        public HeightTestResponse()
        {
            this.result = false;
        }

        public HeightTestResponse(bool result)
        {
            this.result = result;
        }

        public static HeightTestResponse Deserialize(MessageDeserializer deserializer) => new HeightTestResponse(deserializer);

        private HeightTestResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "HeightTestResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
